output_path = "/tmp" # Path to write output fast5 to
global_mean_read_length = 20000 #optional
random_seed = 10
target_yield = 100000000
working_pore_percent = 90 # optional (default 85)
pore_type = "R9" #Optional, one of R10 or R9, default R9
pod5 = false
vbz_plugin = "static/vbz_plugin"

[parameters]
sample_name = "my_sample_name"
experiment_name = "my_experiment_name"
flowcell_name = "my_flowcell_name"
experiment_duration = 4800 # unused currently
device_id = "my_device_id"
position = "my_position"
break_read_ms = 1000 # optional,, default 400

cert_dir = "static/tls_certs"
channels = 512
manager_port = 10000
position_port = 10001

[[sample]]
name = "Sample1"
input_genome = "/path/to/genome/squiggle.npy" # Path to (directory of) pregenerated squiggle file(s)
mean_read_length = 40000.0
weight = 1
weights_files = ["/path/to/distribution_file_1.json"] #optional
amplicon = false # Not a PCR based run # optional
barcodes = ["Barcode01", "Barcode02"] # optional
barcode_weights = [1,2] # Optional
uneven = false # Optional

[[sample]]
name = "Sample2"
input_genome = "/path/to/genome_suiggles/" # Contains 2 squiggles
mean_read_length = 40000.0
weight = 1
weights_files = ["/path/to/distribution_file_1.json", "/path/to/distribution_file_2.json"] #optional - must match number of files represented in `input_genome`
amplicon = false # Not a PCR based run # optional
barcodes = ["Barcode03", "Barcode04"] # optional
barcode_weights = [1,2] # Optional
uneven = false # Optional