output_path = "/tmp/"
target_yield = 100000000000
working_pore_percent = 85
pore_type = "R9"
nucleotide_type = "RNA"
pod5 = false
vbz_plugin = "vbz_plugin"
kmer_model = "static/rna_r9.4_180mv_70bps/5mer_levels_v1.txt"

[parameters]
sample_name = "wtc11"
experiment_name = "wtc11_transcript"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Mechamaru"
position = "Kyoto"
sample_rate = 3000

cert_dir = "static/tls_certs"
channels = 512
manager_port = 10000
position_port = 10001

[[sample]]
name = "Human"
input_genome = "docker/squiggle_arrs/gencode.v44.transcripts.wtc11.fa"
mean_read_length = 1300
weight = 1
weights_files = ["docker/squiggle_arrs/gencode.v44.transcripts.wtc11.dist.json"]
amplicon = true
