output_path = "/tmp/"
global_mean_read_length = 15000
target_yield = 100000000000
working_pore_percent = 85
pore_type = "R10"
nucleotide_type = "DNA"
pod5 = true
vbz_plugin = "vbz_plugin"
kmer_model = "static/dna_r10.4.1_e8.2_400bps/R10_model.tsv"

[parameters]
sample_name = "test"
experiment_name = "test_2_bacteria"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"
sample_rate = 4000

cert_dir = "static/tls_certs"
channels = 512
manager_port = 10000
position_port = 10001

[[sample]]
name = "Bacteria 1"
input_genome = "docker/squiggle_arrs/mixed_ref.fa"
mean_read_length = 10000
weight = 1
barcodes = ["Barcode01", "Barcode02", "Barcode03"]
barcode_weights = [1, 2, 3]
