output_path = "/tmp/"
pore_type = "R9"
pod5 = false
vbz_plugin = "vbz_plugin"
kmer_model = ""
prefix_squiggle = ""

[parameters]
sample_name = "test"
experiment_name = "test_2_bacteria"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"

cert_dir = "static/tls_certs"
channels = 512
manager_port = 10000
position_port = 10001

[[sample]]
input_genome = "squiggle_arrs/monkeypox/"
mean_read_length = 20000
weights_file = "squiggle_arrs/monkeypox/distributions.json"
amplicon = true
