output_path = "/tmp/"
random_seed = 10
pore_type = "R9"
pod5 = false
vbz_plugin = "static/vbz_plugin"

[parameters]
sample_name = "test"
experiment_name = "test_mpv"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"

cert_dir = "static/tls_certs"
channels = 512
manager_port = 10000
position_port = 10001

[[sample]]
name = "MonkeyPox"
weight = 1
input_genome = "squiggle_arrs/monkeypox_barcoded/"
mean_read_length = 20000
amplicon = true
barcodes = ["Barcode01", "Barcode02", "Barcode03"]
barcode_weights = [1, 2, 3]
uneven = true
